### ISSUE TITLE
Compile errors on new project (and examples)

### ISSUE THREAD

**Issue by drewlwhitney** [HaoboGu/rmk#971]
I just tried setting up RMK for the first time and I'm getting some compile-time errors. This happens with a new project for the `xiao_ble` and with the `Sessile`. It seems to be a type error in the `rmk` crate.

# Reproduce
`rustc` version is `rustc 1.97.1 (8bab26f4f 2026-07-14)`.

1. Clone the [Sessile RMK firmware](https://github.com/willpuckett/sessile)
2. `cd` into the `rmk` directory
3. Run `cargo build`

# Full Output
```
   Compiling rmk v0.8.2
error[E0308]: mismatched types
   --> /home/drewl/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rmk-0.8.2/src/direct_pin.rs:149:34
    |
149 |             let _ = select_slice(pin!(futs.as_mut_slice())).await;
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Pin<&mut [impl Future<Output = ...>]>`, found `Pin<&mut &mut [...]>`
    |
    = note: expected struct `core::pin::Pin<&mut _>`
               found struct `core::pin::Pin<&mut &mut _>`

error[E0308]: mismatched types
   --> /home/drewl/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rmk-0.8.2/src/direct_pin.rs:157:34
    |
157 |             let _ = select_slice(pin!(futs.as_mut_slice())).await;
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Pin<&mut [impl Future<Output = ...>]>`, found `Pin<&mut &mut [...]>`
    |
    = note: expected struct `core::pin::Pin<&mut _>`
               found struct `core::pin::Pin<&mut &mut _>`

error[E0308]: mismatched types
   --> /home/drewl/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rmk-0.8.2/src/matrix.rs:289:30
    |
289 |         let _ = select_slice(pin!(futs.as_mut_slice())).await;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Pin<&mut [impl Future<Output = ...>]>`, found `Pin<&mut &mut [...]>`
    |
    = note: expected struct `core::pin::Pin<&mut _>`
               found struct `core::pin::Pin<&mut &mut _>`

error[E0308]: mismatched types
   --> /home/drewl/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rmk-0.8.2/src/matrix.rs:317:30
    |
317 |         let _ = select_slice(pin!(futs.as_mut_slice())).await;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Pin<&mut [impl Future<Output = ...>]>`, found `Pin<&mut &mut [...]>`
    |
    = note: expected struct `core::pin::Pin<&mut _>`
               found struct `core::pin::Pin<&mut &mut _>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rmk` (lib) due to 4 previous errors
```

___

Can anyone else reproduce this locally, and if so, what do we need to do to fix it?

**Comment by drewlwhitney** [comment]
Found the reason for the issue: I'm on `rustc 1.97.1`. In `1.97.0`, they removed deref coercions in `pin!`, so the `&mut &mut` is not being derefed into a `&mut`. I can build using `1.96.1` for now, but we should fix this if possible. I can see about submitting a pull request to fix it.

Thanks!

**Comment by HaoboGu** [comment]
Thanks for the issue. Yes the current version doesn't compile on rustc 1.97. Reverting to rustc 1.96 works.

**Comment by drewlwhitney** [comment]
Gotcha. Would you be interested in a PR to resolve the issue? I think it should just be as simple as adding an `*` somewhere. I'll peek at it tomorrow.

Also, awesome software. Really happy with the setup process and configuration through a TOML file, the keyboard just works

**Comment by drewlwhitney** [comment]
It seems the latest version of the `rmk` crate has fixed this issue already, so I'll just use `1.96.1` until the latest version is released. Thanks!
